### ISSUE TITLE
UI monitoring settings are not all traced

### ISSUE THREAD

**Issue by vogella** [vogellacompany/PreferencesSpy#8]
![tracing](https://cloud.githubusercontent.com/assets/139910/5643295/b7b54994-9656-11e4-947b-0b20e550fb4e.png)

For example if I change the "Error threshold (ms)" this is not traced

**Comment by vogella** [comment]
Here is the key that is not reported:

/instance/org.eclipse.ui.monitoring/long_event_error_threshold=500

**Comment by SimonScholz** [comment]
Resolved this issue with commit Idd9bf0ccb97819ece6e0cca8af777895a13eee87

**Comment by vogella** [comment]
Thanks. FYI: You can close an issue directly via the commit, e.g. by using 

Close #8

in the commit message. This has the advantage to link the issue directly with the commit.

**Comment by SimonScholz** [comment]
Ok, thanks for the hint :)
