### ISSUE TITLE
Can't find the Preferences Spy view

### ISSUE THREAD

**Issue by rherrmann** [vogellacompany/PreferencesSpy#9]
After installing the feature into Eclipse 4.4 from the software site mentioned in the repostories README, the 'Show View' dialog does not list a view labelled 'Preference Spy'.

The installation completes without errors and after restarting the IDE, the feature appears in the 'Installation Details' dialog. The Eclipse installations are nothing fancy either, I tried with 'Eclipse for RAP/RCP 4.4' and 'Eclipse SDK 4.4', in both cases the view does not show up.

Am I missing something obvious?

**Comment by SimonScholz** [comment]
Thank you for pointing at this issue.

I just added a note to the readme:
"The Preference Spy is only available via "Quick access" (Ctrl + 3) before Eclipse 4.5 M5"

By the way the preference spy will be added to the E4 spies soon and therefore will also be available in the Spy Window.
